library(dplyr)
library(tidyverse)
library(ggplot2)

#' Read Fitbit data
#'
#' Reads the CSV generated by exporting the data from Fitbit
#' @param file Location of the exported CSV file 
#' @return The data as a DataFrame
#' @export
read_fitbit_data <- function(file) {
  data <- read.csv(file, header=TRUE);
  return(data);
}


#' Calculate weekly stats
#' 
#' Aggregates stats to create weekly totals and averages. This method can be 
#' used to aggregate the data for multiple users, or can be filtered for a 
#' single user.
#' @param df Fitbit data as a DataFrame
#' @param stat_col DataFrame statistic column name to be aggregated
#' @param filter_id If specified, will generate stats for only this Id
#' @param id_col Column name that uniquely identifies a user; default = "Id"
#' @param date_col Column name for the statistic date/time; default = "ActivityDate"
#' @return The weekly aggregated data with total_ and avg_ prefixed columns.
#' @export
calculate_weekly_stats <- function(df, stat_col, filter_id = NULL, id_col="Id", date_col="ActivityDate" ) {
  activity_date <-  as.Date(df[[date_col]], "%m/%d/%Y")
  
  stats <- data.frame(id = df[[id_col]], activity_date, stat_col = df[[stat_col]])
  
  stats$week_num <- as.numeric(strftime(stats$activity_date, format = "%V")) 
  
  total_col_name <- paste("total_", stat_col, sep = "")
  avg_col_name <- paste("avg_", stat_col, sep = "")
  
  if (missing(filter_id)) {
    stat_summary <- stats %>%
      group_by(id, week_num)
  } else {
    stat_summary <- stats %>%
      filter(id == filter_id) %>%
      group_by(week_num)
  }
  stat_summary <- stat_summary %>%
    summarize(days = n(),
              total_stat = sum(stat_col),
              average_stat = mean(stat_col)) %>%
    rename_at("total_stat", ~ total_col_name) %>%
    rename_at("average_stat", ~ avg_col_name) ; 
  
  return(stat_summary);
}


#' Plot weekly trend
#' 
#' Calculates the weekly stats for the specified column and plots it against the 
#' week number to provide a picture of the trend.
#' @param df Fitbit data as a DataFrame
#' @param stat_col DataFrame statistic column name to be tracked
#' @param filter_id User Id for which to generate the trendline
#' @param id_col Column name that uniquely identifies a user; default = "Id"
#' @param date_col Column name for the statistic date/time; default = "ActivityDate"
#' @return A list of plots of the total and average weekly trend, respectively.
#' @export
plot_weekly_trend <- function(df, stat_col, filter_id, id_col="Id", date_col="ActivityDate" ) {
  stat_summary <- calculate_weekly_stats(df, stat_col, filter_id, id_col, date_col)
  
  total_col_name <- paste("total_", stat_col, sep = "")
  avg_col_name <- paste("avg_", stat_col, sep = "")
  
  p1 <- ggplot(stat_summary, aes(x = as.numeric(week_num), y = .data[[total_col_name]])) +
    geom_point() +
    geom_line() 
  p2 <- ggplot(stat_summary, aes(x = as.numeric(week_num), y = .data[[avg_col_name]])) +
    geom_point() +
    geom_line() 
  return(list(p1, p2))
}


#' Plot active minutes weekly trend
#' 
#' This is a specialized plot which shows the trend of time spent in various 
#' intensity states (sedentary, lightly active, fairly active, very active).
#' It is intended to highlight activity trends over time.
#' @param df Fitbit data as a DataFrame
#' @param filter_id User Id for which to generate the trendline
#' @param id_col Column name that uniquely identifies a user; default = "Id"
#' @param date_col Column name for the statistic date/time; default = "ActivityDate"
#' @param very_col Column name for very active minutes; default = "VeryActiveMinutes"
#' @param fairly_col Column name for fairly active minutes; default = "FairlyActiveMinutes"
#' @param lightly_col Column name for lightly active minutes; default = "LightlyActiveMinutes"
#' @param sedentary_col Column name for sedentary minutes; default = "SedentaryMinutes"
#' @return A stacked bar chart of minutes of activity intensity over time.
#' @export
plot_activity_minute_trend <- function(df, filter_id, 
                       id_col = "Id", date_col="ActivityDate", 
                       very_col="VeryActiveMinutes", 
                       fairly_col="FairlyActiveMinutes", 
                       lightly_col="LightlyActiveMinutes", 
                       sedentary_col="SedentaryMinutes" ) {
  activity_date <-  as.Date(df[[date_col]], "%m/%d/%Y")
  
  stats <- data.frame(id = df[[id_col]], activity_date, 
                      very_col = df[[very_col]],
                      fairly_col = df[[fairly_col]],
                      lightly_col = df[[lightly_col]],
                      sedentary_col = df[[sedentary_col]])
  
  stats$week_num <- strftime(stats$activity_date, format = "%V")
  
  stat_summary <- stats %>%
    filter(id == filter_id) %>%
    group_by(week_num) %>%
    summarize(days = n(),
              avg_very = mean(very_col),
              avg_fairly = mean(fairly_col),
              avg_lightly = mean(lightly_col),
              avg_sedentary = mean(sedentary_col)) %>%
    pivot_longer(
      cols = starts_with("avg_"),  # Selects columns that start with 'avg_'
      names_to = "activity_type",  # New column for activity types
      values_to = "minutes",       # New column for corresponding values
      names_prefix = "avg_"        # Remove the prefix 'avg_' from the activity type names
    )
  
  p <- ggplot(stat_summary, aes(x = week_num, y = minutes, fill = activity_type)) +
    geom_bar(stat = "identity", position = "stack") +
    labs(title = "Activity Minutes by Week",
         x = "Week Number",
         y = "Minutes",
         fill = "Activity Type") +
    theme_minimal()
  return(p)
}

